[package]
name = "validator"
version = "0.1.0"
authors = ["Tristram Gräbener <tristramg@gmail.com>"]

[dependencies]
chrono = "0.4"
failure = "0.1"
failure_derive = "0.1"
geo = "0.8.2"
gotham = "0.2.1"
gotham_derive = "0.2.1"
gtfs-structures = "0.4.1"
hyper = "0.11"
itertools = "0.7.8"
mime = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.2"
structopt-derive = "0.2"
