version: 2

jobs:
  build:
    docker:
      - image: rust:latest

    steps:
      - checkout
      - run: rustup component add rustfmt-preview clippy
      - run: cargo fmt --all -- --check
      - run: cargo clippy
      - run: cargo build
      - run: cargo test
